spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prospero-server
    #spring_boot_security
    username: rbyxnvsunm
    #postgres
    password: OHJUT872VJER83PY$
    #12345678pP
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: prospero-database
    #postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: i18n/messages
server:
  port: 80